services:
  visu:
    build: ./visu
    ports:
      - 8050:8050
    volumes:
      - /home/nuc/wifi-scanner/data/data.csv:/app/track_points.csv:ro #set path of folder data
    environment:
      -  SSID=eduroam #routername to visu


  scanner:
    container_name: scanner
    build: 
      context: ./scanner/
    privileged: true
    stdin_open: true 
    tty: true   
    network_mode: "host"
    environment:
      -  WIFI_INTERFACE_NAME=wlx60e327070396 #set interface name. ip a
    volumes:
      # - data:/app/data/
      - /home/nuc/wifi-scanner/data/data.csv:/app/data/data.csv:rw
    # restart: always




# volumes:
#   data:
#     driver_opts:
#         type: none
#         device: /home/nuc/wifi-scanner/data #set path of folder data
#         o: bind


      # Dropdown menu for ssid
      # Bar chart for channels and strength
