services:
  visu:
    build: ./visu
    ports:
      - 8050:8050
    volumes:
      - /home/jonas/project/data/data.csv:/app/track_points.csv:ro #set path of folder data
    environment:
      -  SSID=2Girls1Router #routername to visu


  scanner:
    container_name: scanner
    build: 
      context: ./scanner/
    privileged: true
    stdin_open: true 
    tty: true   
    network_mode: "host"
    environment:
      -  WIFI_INTERFACE_NAME=wlx503eaad2a0b0 #set interface name. ip a
    volumes:
      - data:/app/data/
    restart: always




volumes:
  data:
    driver_opts:
        type: none
        device: /home/jonas/project/data #set path of folder data
        o: bind


      # Dropdown menu for ssid
      # Bar chart for channels and strength