services:
  visu_live:
    build: ./visu/live
    ports:
      - 8050:8050
    volumes:
      - /home/jonas/project/Wifi-Scanner/data/dataTest2.csv:/app/track_points.csv:rw #set path of folder data
    stop_grace_period: 1s
    labels:
      - 'live'

  visu_toggle:
    build: ./visu/toggle
    ports:
      - 8050:8050
    volumes:
      - /home/jonas/project/Wifi-Scanner/data/dataTest2.csv:/app/track_points.csv:rw #set path of folder data
    stop_grace_period: 1s
    labels:
      - 'toggle'
    
  visu_test:
    build: ./visu/test
    ports:
      - 8050:8050
    volumes:
      - /home/jonas/project/Wifi-Scanner/data/dataTest2.csv:/app/track_points.csv:rw #set path of folder data
    stop_grace_period: 1s
    labels:
      - 'test'




  scanner:
    container_name: scanner
    build: 
      context: ./scanner/
    privileged: true
    stdin_open: true 
    tty: true   
    network_mode: "host"
    environment:
      -  WIFI_INTERFACE_NAME=wlx503eaad2a0b0 #set interface name. ip a
    volumes:
      - data:/app/data/
    restart: always
    stop_grace_period: 1s




volumes:
  data:
    driver_opts:
        type: none
        device: /home/jonas/project/Wifi-Scanner/data #set path of folder data
        o: bind



      # Bar chart for channels and strength